// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf1C07sTTTSysn-xd6EWDCVHrnsjnuAqw',
    appId: '1:885312839706:web:04e6974890c033f71ef1a3',
    messagingSenderId: '885312839706',
    projectId: 'wajlc-e1fee',
    authDomain: 'wajlc-e1fee.firebaseapp.com',
    storageBucket: 'wajlc-e1fee.firebasestorage.app',
    measurementId: 'G-RRN6BJNBYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr7lgafYhf6JDd7Z_NytKajx7HjcQlRa0',
    appId: '1:885312839706:android:468e20d77961f3ed1ef1a3',
    messagingSenderId: '885312839706',
    projectId: 'wajlc-e1fee',
    storageBucket: 'wajlc-e1fee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr7lgafYhf6JDd7Z_NytKajx7HjcQlRa0',
    appId: '1:885312839706:ios:468e20d77961f3ed1ef1a3',
    messagingSenderId: '885312839706',
    projectId: 'wajlc-e1fee',
    storageBucket: 'wajlc-e1fee.firebasestorage.app',
    iosBundleId: 'com.miraimagiclab.toriiApp',
  );
}
