import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:torii_mobile/features/auth/providers/auth_providers.dart';
import 'package:torii_mobile/features/auth/models/auth_state_sealed.dart';
import 'package:torii_mobile/core/constants/app_design_system.dart';
import 'package:torii_mobile/core/widgets/widgets.dart';
import 'package:torii_mobile/core/widgets/zen_background.dart';
import 'package:torii_mobile/core/widgets/animations/entry_animation.dart';

class TwoFactorVerifyPage extends ConsumerStatefulWidget {
  const TwoFactorVerifyPage({super.key});

  @override
  ConsumerState<TwoFactorVerifyPage> createState() => _TwoFactorVerifyPageState();
}

class _TwoFactorVerifyPageState extends ConsumerState<TwoFactorVerifyPage> {
  final List<TextEditingController> _controllers = List.generate(6, (_) => TextEditingController());
  final List<FocusNode> _focusNodes = List.generate(6, (_) => FocusNode());
  bool _isBackupMode = false;
  final TextEditingController _backupController = TextEditingController();

  @override
  void dispose() {
    for (var controller in _controllers) {
      controller.dispose();
    }
    for (var node in _focusNodes) {
      node.dispose();
    }
    _backupController.dispose();
    super.dispose();
  }

  String get _otpCode => _controllers.map((c) => c.text).join();

  void _onVerify() {
    if (_isBackupMode) {
      if (_backupController.text.isNotEmpty) {
        ref.read(authStateProvider.notifier).verify2FA(_backupController.text, isBackupCode: true);
      }
    } else {
      if (_otpCode.length == 6) {
        ref.read(authStateProvider.notifier).verify2FA(_otpCode);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final authState = ref.watch(authStateProvider);
    
    // Redirect if authenticated
    if (authState is AuthAuthenticated) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (mounted) context.go('/');
      });
    }

    String? error;
    if (authState is AuthTwoFactorRequired) {
      error = authState.error;
    } else if (authState is AuthError) {
      error = authState.message;
    }

    return Scaffold(
      backgroundColor: AppColors.background,
      body: ZenBackground(
        child: SafeArea(
          child: SingleChildScrollView(
            padding: const EdgeInsets.symmetric(horizontal: AppSpacing.xl),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                const SizedBox(height: 60),
                
                // Icon Header
                EntryAnimation(
                  index: 0,
                  child: Container(
                    padding: const EdgeInsets.all(20),
                    decoration: BoxDecoration(
                      color: AppColors.primary.withOpacity(0.1),
                      shape: BoxShape.circle,
                    ),
                    child: Icon(
                      _isBackupMode ? Icons.vpn_key_rounded : Icons.security_rounded,
                      size: 40,
                      color: AppColors.primary,
                    ),
                  ),
                ),
                const SizedBox(height: 32),

                // Title & Subtitle
                EntryAnimation(
                  index: 1,
                  child: Column(
                    children: [
                      Text(
                        _isBackupMode ? 'BACKUP_PROTOCOL' : 'NEURAL_VERIFICATION',
                        style: const TextStyle(
                          fontFamily: AppTypography.fontFamilySerif,
                          fontWeight: AppTypography.black,
                          fontSize: 24,
                          letterSpacing: -0.5,
                        ),
                      ),
                      const SizedBox(height: 12),
                      Text(
                        _isBackupMode 
                          ? 'Enter your 8-character recovery codes to bypass standard authentication.'
                          : 'Enter the security code generated by your authenticator app.',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: AppColors.textTertiary,
                          fontSize: 14,
                          height: 1.5,
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 48),

                // Main Input Area
                EntryAnimation(
                  index: 2,
                  child: _isBackupMode ? _buildBackupInput() : _buildOtpInput(),
                ),

                if (error != null) ...[
                  const SizedBox(height: 16),
                  EntryAnimation(
                    index: 3,
                    child: Text(
                      error,
                      style: const TextStyle(color: Color(0xFFE63946), fontSize: 12, fontWeight: AppTypography.bold),
                    ),
                  ),
                ],

                const SizedBox(height: 48),

                // Actions
                EntryAnimation(
                  index: 4,
                  child: Column(
                    children: [
                      ZenButton(
                        text: 'AUTHORIZE_ACCESS',
                        onPressed: _onVerify,
                        isLoading: authState is AuthLoading,
                        isFullWidth: true,
                      ),
                      const SizedBox(height: 24),
                      TextButton(
                        onPressed: () {
                          setState(() {
                            _isBackupMode = !_isBackupMode;
                             error = null;
                          });
                        },
                        child: Text(
                          _isBackupMode ? 'USE_AUTHENTICATOR_APP' : 'LOST_ACCESS_TO_APP?',
                          style: TextStyle(
                            fontSize: 10,
                            fontWeight: AppTypography.black,
                            color: AppColors.textTertiary,
                            letterSpacing: 2.0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                
                const SizedBox(height: 40),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildOtpInput() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: List.generate(6, (index) {
        return SizedBox(
          width: 45,
          child: TextField(
            controller: _controllers[index],
            focusNode: _focusNodes[index],
            keyboardType: TextInputType.number,
            textAlign: TextAlign.center,
            maxLength: 1,
            style: const TextStyle(fontSize: 24, fontWeight: AppTypography.black, color: AppColors.primary),
            decoration: InputDecoration(
              counterText: "",
              enabledBorder: UnderlineInputBorder(
                borderSide: BorderSide(color: AppColors.grey300, width: 2),
              ),
              focusedBorder: const UnderlineInputBorder(
                borderSide: BorderSide(color: AppColors.primary, width: 2),
              ),
            ),
            onChanged: (value) {
              if (value.isNotEmpty && index < 5) {
                _focusNodes[index + 1].requestFocus();
              } else if (value.isEmpty && index > 0) {
                _focusNodes[index - 1].requestFocus();
              }
              if (_otpCode.length == 6) {
                _onVerify();
              }
            },
          ),
        );
      }),
    );
  }

  Widget _buildBackupInput() {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(AppRadius.lg),
        border: Border.all(color: AppColors.grey200),
      ),
      child: TextField(
        controller: _backupController,
        style: const TextStyle(fontFamily: 'Courier', fontWeight: AppTypography.bold, letterSpacing: 2.0),
        textAlign: TextAlign.center,
        decoration: InputDecoration(
          hintText: 'XXXX-XXXX',
          hintStyle: TextStyle(color: AppColors.grey400, letterSpacing: 2.0),
          border: InputBorder.none,
          contentPadding: const EdgeInsets.all(20),
        ),
        onSubmitted: (_) => _onVerify(),
      ),
    );
  }
}
